"""update repositories

Revision ID: 39a97ef2d747
Revises: 1aaf50e45b53
Create Date: 2025-01-03 15:50:01.726589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a97ef2d747'
down_revision = '1aaf50e45b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('db_server', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('db_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('db_user', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('db_password', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('db_password')
        batch_op.drop_column('db_user')
        batch_op.drop_column('db_name')
        batch_op.drop_column('db_server')

    # ### end Alembic commands ###
